#!/bin/sh

. /etc/rc.common

# Set MOUNTPOINT variable if rEFIt is installed on a different volume. You must
# make sure that the volume is mounted when the system shuts down.
# If the volume is not mounted (because it's removable or hidden), then use MOUNTSLICE

MOUNTPOINT=""
EFIFOLDER="/EFI/refind"
EFIFILE="refind_x64.efi"
LABELFILE=""
LABELNAME="rEFInd"
MOUNTSLICE=13
MOUNTCOMMAND=mount_hfs

rEFItLog ()
{
	echo "rEFItBlesser - $1"
	echo "`date`: rEFItBlesser - $1" >> /Users/Shared/rEFItBlesser.log
}

MacOSXBlessed ()
{
	BLESSINFO=$(bless --info 2> /dev/null)
	BLESSEDFILE=$(echo "$BLESSINFO" | grep 'Blessed System File')
	if echo $BLESSEDFILE | grep ' /System/Library/CoreServices/boot.efi' >/dev/null 2>&1 ; then
		return 0
	fi
	return 1
}

StartService ()
{
	rEFItLog "StartService"
	if ! MacOSXBlessed ; then
		rEFItLog "Blessing Mac OS X on Startup"
		bless --folder /System/Library/CoreServices --file /System/Library/CoreServices/boot.efi --setBoot
	fi
	return 0
}

StopService ()
{
	rEFItLog "StopService"
	if MacOSXBlessed ; then
		mounted=0
		if [ -f "$MOUNTPOINT/$EFIFOLDER/$EFIFILE" ]; then
            rEFItLog "Blessing rEFInd on Startup"
            bless --setBoot --folder "$EFIFOLDER" --file "$EFIFOLDER/$EFIFILE"
		else
			rEFItLog "$LABELNAME not found at \"$MOUNTPOINT/$EFIFOLDER/$EFIFILE\""
			mount >> /Users/Shared/rEFItBlesser.log
		fi

	fi
	return 0
}

RestartService ()
{
	return 0
}

RunService "$1"
